[colors]
foreground = "#bbbac1"
background = "#171719"
# background = "#111113" # alternate, darker bg
cursor_bg = "#bbbac1"
cursor_border = "#555568"
cursor_fg = "#171719"
selection_bg = "#2a2a31"
selection_fg = "#a8a6de"
split = "#555568"
compose_cursor = "#abbceb"
scrollbar_thumb = "${grey}"

ansi = ["#555568", "#5C5B8D", "#494966", "#5A6B9A", "#846178", "#856A5E", "#44676C", "#79797E"]
brights = ["#9b99a3", "#8a88db", "#6b6b99", "#86a3f0", "#cc93b8", "#cfa18c", "#629da3", "#bbbac1"]

[colors.tab_bar]
inactive_tab_edge = "#79797E"
background = "#171719"

[colors.tab_bar.active_tab]
fg_color = "#abbceb"
bg_color = "#2a2a31"

[colors.tab_bar.inactive_tab]
fg_color = "#555568"
bg_color = "#1d1d22"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#555568"
bg_color = "#1d1d22"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#abbceb"
bg_color = "#2a2a31"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#abbceb"
bg_color = "#171719"

[metadata]
aliases = []
name = "ICECLIMBER"
url = "https://wezfurlong.org/wezterm/config/files.html"
upstream = "https://github.com/cdmill/neomodern.nvim/raw/main/extras/wezterm/iceclimber.toml"
author = "Casey Miller"
