# COFFEECAT Alacritty Colors
# Default colors
[colors.primary]
background = '#1f1e1d'
foreground = '#bbbac1'

#[colors.cursor]
#cursor = '#bbbac1'
#text = '#1f1e1d'

# Normal colors
[colors.normal]
black = '#191818'
red = '#d47b7d'
green = '#8fc490'
yellow = '#e8cea0'
blue = '#96b1fa'
magenta = '#9b9af5'
cyan = '#b39581'
white = '#bbbac1'

# Bright colors
[colors.bright]
black = '#6a6a6a'
red = '#d47b7d'
green = '#8fc490'
yellow = '#e8cea0'
blue = '#96b1fa'
magenta = '#e3afd1'
cyan = '#b39581'
white = '#bbbac1'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#e3a968'

[[colors.indexed_colors]]
index = 17
color = '#9b9af5'
