# COFFEECAT Alacritty Colors
# Default colors
[colors.primary]
background = '#1e1d1c'
foreground = '#bbbac1'

#[colors.cursor]
#cursor = '#bbbac1'
#text = '#1e1d1c'

# Normal colors
[colors.normal]
black = '#121110'
red = '#d67287'
green = '#8ab56d'
yellow = '#ebc686'
blue = '#a2bafa'
magenta = '#cfa991'
cyan = '#78bfc4'
white = '#bbbac1'

# Bright colors
[colors.bright]
black = '#6a6a6a'
red = '#d67287'
green = '#8ab56d'
yellow = '#ebc686'
blue = '#a2bafa'
magenta = '#ebabd5'
cyan = '#78bfc4'
white = '#bbbac1'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#e8a85f'

[[colors.indexed_colors]]
index = 17
color = '#cfa991'
