# name: GYOKURO colors for Alacritty
# url: https://github.com/alacritty/alacritty
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/alacritty/gyokuro.toml
# author: Casey Miller

# Default colors
[colors.primary]
background = '#1b1c1d'
# alternate, darker background = '#161617'
foreground = '#bbbac1'

#[colors.cursor]
#cursor = '#bbbac1'
#text = '#1b1c1d'

# Normal colors
[colors.normal]
black = '#767777'
red = '#4F654C'
green = '#6C7355'
yellow = '#5B6078'
blue = '#5E725B'
magenta = '#8B7177'
cyan = '#50616F'
white = '#7B7B7F'

# Bright colors
[colors.bright]
black = '#b08c7d'
red = '#72966c'
green = '#a2ad7b'
yellow = '#868db5'
blue = '#8bab85'
magenta = '#d6a9b3'
cyan = '#748fa6'
white = '#bbbac1'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#161617'

[[colors.indexed_colors]]
index = 17
color = '#a69e6f'
