# ICECLIMBER Alacritty Colors
# Default colors
[colors.primary]
background = '#171719'
foreground = '#bbbac1'

#[colors.cursor]
#cursor = '#bbbac1'
#text = '#171719'

# Normal colors
[colors.normal]
black = '#2d2d2f'
red = '#e67e80'
green = '#7da77e'
yellow = '#7da77e'
blue = '#86a3f0'
magenta = '#8a88db'
cyan = '#559ba3'
white = '#bbbac1'

# Bright colors
[colors.bright]
black = '#555568'
red = '#e67e80'
green = '#7da77e'
yellow = '#7da77e'
blue = '#86a3f0'
magenta = '#e89bce'
cyan = '#559ba3'
white = '#bbbac1'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#e3a462'

[[colors.indexed_colors]]
index = 17
color = '#abbceb'
