# name: ICECLIMBER colors for Alacritty
# url: https://github.com/alacritty/alacritty
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/alacritty/iceclimber.toml
# author: Casey Miller

# Default colors
[colors.primary]
background = '#171719'
# alternate, darker background = '#111113'
foreground = '#bbbac1'

#[colors.cursor]
#cursor = '#bbbac1'
#text = '#171719'

# Normal colors
[colors.normal]
black = '#555568'
red = '#e67e80'
green = '#465D4B'
yellow = '#ad9368'
blue = '#86a3f0'
magenta = '#6b6b99'
cyan = '#44676C'
white = '#79797E'

# Bright colors
[colors.bright]
black = '#555568'
red = '#cc93b8'
green = '#658c6d'
yellow = '#cfa18c'
blue = '#abbceb'
magenta = '#a8a6de'
cyan = '#629da3'
white = '#bbbac1'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#111113'

[[colors.indexed_colors]]
index = 17
color = '#abbceb'
