# name: ICECLIMBER colors for Alacritty
# url: https://github.com/alacritty/alacritty
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/alacritty/iceclimber.toml
# author: Casey Miller

# Default colors
[colors.primary]
background = '#171719'
# alternate, darker background = '#111113'
foreground = '#bbbac1'

#[colors.cursor]
#cursor = '#bbbac1'
#text = '#171719'

# Normal colors
[colors.normal]
black = '#555568'
red = '#5C5B8D'
green = '#494966'
yellow = '#5A6B9A'
blue = '#846178'
magenta = '#856A5E'
cyan = '#44676C'
white = '#79797E'

# Bright colors
[colors.bright]
black = '#9b99a3'
red = '#8a88db'
green = '#6b6b99'
yellow = '#86a3f0'
blue = '#cc93b8'
magenta = '#cfa18c'
cyan = '#629da3'
white = '#bbbac1'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#111113'

[[colors.indexed_colors]]
index = 17
color = '#abbceb'
