# name: ROSEPRIME colors for Alacritty
# url: https://github.com/alacritty/alacritty
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/alacritty/roseprime.toml
# author: Casey Miller

# Default colors
[colors.primary]
background = '#121315'
# alternate, darker background = '#111111'
foreground = '#adadcc'

#[colors.cursor]
#cursor = '#adadcc'
#text = '#121315'

# Normal colors
[colors.normal]
black = '#666a82'
red = '#436285'
green = '#857164'
yellow = '#6172A0'
blue = '#7D6166'
magenta = '#83685C'
cyan = '#6F566A'
white = '#6F6F83'

# Bright colors
[colors.bright]
black = '#838196'
red = '#6397cf'
green = '#d2af98'
yellow = '#95b1fc'
blue = '#c4959c'
magenta = '#cfa18c'
cyan = '#ad82a2'
white = '#adadcc'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#111111'

[[colors.indexed_colors]]
index = 17
color = '#a8a6f5'
